# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RTEDlg.ui'
#
# Created: Sat Nov 17 07:26:43 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RTEDlg(object):
    def setupUi(self, RTEDlg):
        RTEDlg.setObjectName(_fromUtf8("RTEDlg"))
        RTEDlg.resize(1222, 572)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RTEDlg.sizePolicy().hasHeightForWidth())
        RTEDlg.setSizePolicy(sizePolicy)
        RTEDlg.setMinimumSize(QtCore.QSize(1222, 572))
        RTEDlg.setMaximumSize(QtCore.QSize(1222, 572))
        RTEDlg.setWhatsThis(_fromUtf8(""))
        self.line = QtGui.QFrame(RTEDlg)
        self.line.setGeometry(QtCore.QRect(260, 10, 20, 551))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.smaMpl = MatplotlibWidget(RTEDlg)
        self.smaMpl.setGeometry(QtCore.QRect(280, 10, 461, 271))
        self.smaMpl.setObjectName(_fromUtf8("smaMpl"))
        self.emaMpl = MatplotlibWidget(RTEDlg)
        self.emaMpl.setGeometry(QtCore.QRect(280, 290, 461, 271))
        self.emaMpl.setObjectName(_fromUtf8("emaMpl"))
        self.lwmaMpl = MatplotlibWidget(RTEDlg)
        self.lwmaMpl.setGeometry(QtCore.QRect(750, 10, 461, 271))
        self.lwmaMpl.setObjectName(_fromUtf8("lwmaMpl"))
        self.tmaMpl = MatplotlibWidget(RTEDlg)
        self.tmaMpl.setGeometry(QtCore.QRect(750, 290, 461, 271))
        self.tmaMpl.setObjectName(_fromUtf8("tmaMpl"))
        self.groupBox = QtGui.QGroupBox(RTEDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 115))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 23, 231, 25))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.connectButton = QtGui.QPushButton(self.widget)
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.horizontalLayout.addWidget(self.connectButton)
        self.disconnectButton = QtGui.QPushButton(self.widget)
        self.disconnectButton.setObjectName(_fromUtf8("disconnectButton"))
        self.horizontalLayout.addWidget(self.disconnectButton)
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(10, 50, 231, 48))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pfLabel = QtGui.QLabel(self.widget1)
        self.pfLabel.setWordWrap(True)
        self.pfLabel.setObjectName(_fromUtf8("pfLabel"))
        self.gridLayout.addWidget(self.pfLabel, 0, 0, 1, 1)
        self.pfEdit = QtGui.QLineEdit(self.widget1)
        self.pfEdit.setObjectName(_fromUtf8("pfEdit"))
        self.gridLayout.addWidget(self.pfEdit, 0, 1, 1, 1)
        self.tbLabel = QtGui.QLabel(self.widget1)
        self.tbLabel.setWordWrap(True)
        self.tbLabel.setObjectName(_fromUtf8("tbLabel"))
        self.gridLayout.addWidget(self.tbLabel, 1, 0, 1, 1)
        self.tbEdit = QtGui.QLineEdit(self.widget1)
        self.tbEdit.setObjectName(_fromUtf8("tbEdit"))
        self.gridLayout.addWidget(self.tbEdit, 1, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(RTEDlg)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 126, 251, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.startButton = QtGui.QPushButton(self.groupBox_2)
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.verticalLayout_2.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.groupBox_2)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.verticalLayout_2.addWidget(self.stopButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.groupBox_3 = QtGui.QGroupBox(RTEDlg)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 220, 251, 341))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.UTCLabel = QtGui.QLabel(self.groupBox_3)
        self.UTCLabel.setObjectName(_fromUtf8("UTCLabel"))
        self.gridLayout_2.addWidget(self.UTCLabel, 0, 0, 1, 1)
        self.timeEdit = QtGui.QLineEdit(self.groupBox_3)
        self.timeEdit.setText(_fromUtf8(""))
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.gridLayout_2.addWidget(self.timeEdit, 0, 1, 1, 2)
        self.latitudeLabel = QtGui.QLabel(self.groupBox_3)
        self.latitudeLabel.setObjectName(_fromUtf8("latitudeLabel"))
        self.gridLayout_2.addWidget(self.latitudeLabel, 1, 0, 1, 1)
        self.latitudeEdit = QtGui.QLineEdit(self.groupBox_3)
        self.latitudeEdit.setReadOnly(True)
        self.latitudeEdit.setObjectName(_fromUtf8("latitudeEdit"))
        self.gridLayout_2.addWidget(self.latitudeEdit, 1, 1, 1, 2)
        self.longitudeLabel = QtGui.QLabel(self.groupBox_3)
        self.longitudeLabel.setObjectName(_fromUtf8("longitudeLabel"))
        self.gridLayout_2.addWidget(self.longitudeLabel, 2, 0, 1, 1)
        self.longitudeEdit = QtGui.QLineEdit(self.groupBox_3)
        self.longitudeEdit.setReadOnly(True)
        self.longitudeEdit.setObjectName(_fromUtf8("longitudeEdit"))
        self.gridLayout_2.addWidget(self.longitudeEdit, 2, 1, 1, 2)
        self.MSLALabel = QtGui.QLabel(self.groupBox_3)
        self.MSLALabel.setWordWrap(True)
        self.MSLALabel.setObjectName(_fromUtf8("MSLALabel"))
        self.gridLayout_2.addWidget(self.MSLALabel, 3, 0, 1, 1)
        self.seaAltitudeEdit = QtGui.QLineEdit(self.groupBox_3)
        self.seaAltitudeEdit.setReadOnly(True)
        self.seaAltitudeEdit.setObjectName(_fromUtf8("seaAltitudeEdit"))
        self.gridLayout_2.addWidget(self.seaAltitudeEdit, 3, 2, 1, 1)
        self.NumSatLabel = QtGui.QLabel(self.groupBox_3)
        self.NumSatLabel.setWordWrap(True)
        self.NumSatLabel.setObjectName(_fromUtf8("NumSatLabel"))
        self.gridLayout_2.addWidget(self.NumSatLabel, 4, 0, 1, 2)
        self.numSatEdit = QtGui.QLineEdit(self.groupBox_3)
        self.numSatEdit.setReadOnly(True)
        self.numSatEdit.setObjectName(_fromUtf8("numSatEdit"))
        self.gridLayout_2.addWidget(self.numSatEdit, 4, 2, 1, 1)
        self.altitudePressureLabel = QtGui.QLabel(self.groupBox_3)
        self.altitudePressureLabel.setWordWrap(True)
        self.altitudePressureLabel.setObjectName(_fromUtf8("altitudePressureLabel"))
        self.gridLayout_2.addWidget(self.altitudePressureLabel, 5, 0, 1, 2)
        self.altitudePressureEdit = QtGui.QLineEdit(self.groupBox_3)
        self.altitudePressureEdit.setReadOnly(True)
        self.altitudePressureEdit.setObjectName(_fromUtf8("altitudePressureEdit"))
        self.gridLayout_2.addWidget(self.altitudePressureEdit, 5, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.descentRateEdit = QtGui.QLineEdit(self.groupBox_3)
        self.descentRateEdit.setReadOnly(True)
        self.descentRateEdit.setObjectName(_fromUtf8("descentRateEdit"))
        self.gridLayout_2.addWidget(self.descentRateEdit, 6, 2, 1, 1)
        self.tempLabel = QtGui.QLabel(self.groupBox_3)
        self.tempLabel.setObjectName(_fromUtf8("tempLabel"))
        self.gridLayout_2.addWidget(self.tempLabel, 7, 0, 1, 1)
        self.airTempEdit = QtGui.QLineEdit(self.groupBox_3)
        self.airTempEdit.setReadOnly(True)
        self.airTempEdit.setObjectName(_fromUtf8("airTempEdit"))
        self.gridLayout_2.addWidget(self.airTempEdit, 7, 2, 1, 1)
        self.voltageLabel = QtGui.QLabel(self.groupBox_3)
        self.voltageLabel.setObjectName(_fromUtf8("voltageLabel"))
        self.gridLayout_2.addWidget(self.voltageLabel, 8, 0, 1, 2)
        self.voltageEdit = QtGui.QLineEdit(self.groupBox_3)
        self.voltageEdit.setReadOnly(True)
        self.voltageEdit.setObjectName(_fromUtf8("voltageEdit"))
        self.gridLayout_2.addWidget(self.voltageEdit, 8, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 9, 0, 1, 1)
        self.servo1Edit = QtGui.QLineEdit(self.groupBox_3)
        self.servo1Edit.setReadOnly(True)
        self.servo1Edit.setObjectName(_fromUtf8("servo1Edit"))
        self.gridLayout_2.addWidget(self.servo1Edit, 9, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 10, 0, 1, 1)
        self.servo2Edit = QtGui.QLineEdit(self.groupBox_3)
        self.servo2Edit.setReadOnly(True)
        self.servo2Edit.setObjectName(_fromUtf8("servo2Edit"))
        self.gridLayout_2.addWidget(self.servo2Edit, 10, 2, 1, 1)
        self.UTCLabel.setBuddy(self.timeEdit)
        self.latitudeLabel.setBuddy(self.latitudeEdit)
        self.longitudeLabel.setBuddy(self.longitudeEdit)
        self.MSLALabel.setBuddy(self.seaAltitudeEdit)
        self.NumSatLabel.setBuddy(self.numSatEdit)
        self.altitudePressureLabel.setBuddy(self.altitudePressureEdit)
        self.tempLabel.setBuddy(self.airTempEdit)
        self.voltageLabel.setBuddy(self.voltageEdit)

        self.retranslateUi(RTEDlg)
        QtCore.QMetaObject.connectSlotsByName(RTEDlg)

    def retranslateUi(self, RTEDlg):
        RTEDlg.setWindowTitle(QtGui.QApplication.translate("RTEDlg", "Algorithmic Trading Application", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("RTEDlg", "Connection Details", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("RTEDlg", "&Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnectButton.setText(QtGui.QApplication.translate("RTEDlg", "&Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.pfLabel.setText(QtGui.QApplication.translate("RTEDlg", "Price Feed Port", None, QtGui.QApplication.UnicodeUTF8))
        self.pfEdit.setText(QtGui.QApplication.translate("RTEDlg", "8211", None, QtGui.QApplication.UnicodeUTF8))
        self.tbLabel.setText(QtGui.QApplication.translate("RTEDlg", "Trade Booking Port", None, QtGui.QApplication.UnicodeUTF8))
        self.tbEdit.setText(QtGui.QApplication.translate("RTEDlg", "8212", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RTEDlg", "GUI Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("RTEDlg", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("RTEDlg", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RTEDlg", "Latest Received Data", None, QtGui.QApplication.UnicodeUTF8))
        self.UTCLabel.setText(QtGui.QApplication.translate("RTEDlg", "UTC Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.latitudeLabel.setText(QtGui.QApplication.translate("RTEDlg", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.longitudeLabel.setText(QtGui.QApplication.translate("RTEDlg", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.MSLALabel.setText(QtGui.QApplication.translate("RTEDlg", "Mean sea level altitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.NumSatLabel.setText(QtGui.QApplication.translate("RTEDlg", "Number of satellites tracked", None, QtGui.QApplication.UnicodeUTF8))
        self.altitudePressureLabel.setText(QtGui.QApplication.translate("RTEDlg", "Altitude from pressure sensor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RTEDlg", "Descent Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.tempLabel.setText(QtGui.QApplication.translate("RTEDlg", "Air Temp:", None, QtGui.QApplication.UnicodeUTF8))
        self.voltageLabel.setText(QtGui.QApplication.translate("RTEDlg", "Battery Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RTEDlg", "Servo 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RTEDlg", "Servo 2:", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
